# Generated by Django 4.2 on 2026-02-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='tin',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='TIN'),
        ),
    ]
