# Generated by Django 4.2 on 2026-02-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_add_tin_to_business_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='discounts_enabled',
            field=models.BooleanField(default=False, verbose_name='Discounts Enabled'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='track_inventory',
            field=models.BooleanField(default=True, verbose_name='Track Inventory'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='vat_enabled',
            field=models.BooleanField(default=False, verbose_name='VAT Enabled'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=5, verbose_name='VAT Rate (%)'),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied to this transaction', max_digits=10),
        ),
    ]
