# Generated by Django 4.2 on 2026-02-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_add_settings_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransaction',
            name='discount_id_number',
            field=models.CharField(blank=True, default='', help_text='SC/PWD ID number for audit trail', max_length=50),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='discount_type',
            field=models.CharField(blank=True, default='', help_text='Type of discount (fixed, percent, sc, pwd)', max_length=20),
        ),
    ]
