# Generated by Django 4.2 on 2026-03-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0004_add_discount_type_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='discounts_enabled',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='promo_discount_enabled',
            field=models.BooleanField(default=False, verbose_name='Promo Discount Enabled'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='pwd_discount_enabled',
            field=models.BooleanField(default=True, verbose_name='PWD Discount Enabled'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='pwd_discount_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='PWD Discount Rate (%)'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='sc_discount_enabled',
            field=models.BooleanField(default=True, verbose_name='SC Discount Enabled'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='sc_discount_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='SC Discount Rate (%)'),
        ),
    ]
