# Generated by Django 4.2 on 2026-03-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0005_redesign_discount_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransaction',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
