# Generated by Django 4.2 on 2026-03-19 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0007_add_indexes_and_discount_choices'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='postransaction',
            name='canteen_pos_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='postransaction',
            name='canteen_pos_shift_idx',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='promo_discount_enabled',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='pwd_discount_enabled',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='pwd_discount_rate',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='sc_discount_enabled',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='sc_discount_rate',
        ),
        migrations.RemoveField(
            model_name='paymentgatewayconfig',
            name='qr_image',
        ),
        migrations.RemoveField(
            model_name='postransaction',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='postransaction',
            name='discount_id_number',
        ),
        migrations.RemoveField(
            model_name='postransaction',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='postransaction',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='postransaction',
            name='voided_at',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='discounts_enabled',
            field=models.BooleanField(default=False, verbose_name='Discounts Enabled'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('cashier', 'Cashier')], default='cashier', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='canteen.itemcategory', verbose_name='Item Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, verbose_name='Low Stock Alert Level'),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='api_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
