# Generated by Django 4.2 on 2026-03-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0013_postransaction_vat_exempt_vat_amount'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='officialreceiptcounter',
            new_name='canteen_off_date_d4adf3_idx',
            old_name='canteen_off_date_idx',
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
        migrations.AlterField(
            model_name='categoryvariantgroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='officialreceiptcounter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productvariantgroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
