# Generated by Django 4.2 on 2026-05-10 13:54

from django.db import migrations


def seed_units(apps, schema_editor):
    IngredientUnit = apps.get_model('canteen', 'IngredientUnit')
    units = [
        ('Grams', 'g'),
        ('Kilograms', 'kg'),
        ('Milliliters', 'ml'),
        ('Liters', 'L'),
        ('Pieces', 'pcs'),
        ('Teaspoon', 'tsp'),
        ('Tablespoon', 'tbsp'),
        ('Cups', 'cup'),
        ('Ounces', 'oz'),
        ('Pounds', 'lb'),
        ('Sheets', 'sht'),
        ('Scoops', 'scoop'),
        ('Sachets', 'scht'),
        ('Bottles', 'btl'),
        ('Cans', 'can'),
    ]
    for name, abbreviation in units:
        IngredientUnit.objects.get_or_create(
            abbreviation=abbreviation,
            defaults={'name': name, 'is_active': True}
        )

def unseed_units(apps, schema_editor):
    IngredientUnit = apps.get_model('canteen', 'IngredientUnit')
    abbreviations = ['g','kg','ml','L','pcs','tsp','tbsp','cup','oz','lb','sht','scoop','scht','btl','can']
    IngredientUnit.objects.filter(abbreviation__in=abbreviations).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0015_ingredient_inventory'),
    ]

    operations = [
        migrations.RunPython(seed_units, reverse_code=unseed_units),
    ]
