# Generated by Django 4.2 on 2026-05-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0018_add_non_negative_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='vat_inclusive',
            field=models.BooleanField(default=True, verbose_name='VAT Inclusive Pricing'),
        ),
    ]
