# Generated by Django 4.2 on 2026-05-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0019_businessprofile_vat_inclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='currency',
            field=models.CharField(default='PHP', max_length=10, verbose_name='Currency Code'),
        ),
    ]
