# Generated by Django 5.2.14 on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0021_paymentgatewayconfig_fernet_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='gateway',
            field=models.CharField(
                choices=[('gcash', 'GCash'), ('maya', 'Maya'), ('card', 'Credit/Debit Card')],
                max_length=20,
                unique=True,
            ),
        ),
    ]
