# Generated by Django 5.2.14 on 2026-06-02 07:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0033_user_allowed_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='track_depletion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='current_stock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        # NOTE: makemigrations also wanted an AlterField on
        # postransaction.total_amount_currency (djmoney choices drift,
        # FLAG-065). That drift is intentionally NOT migrated — it is a
        # no-op choices-list expansion from a djmoney version bump. It has
        # been stripped from this migration so 0034 carries only the
        # B8/IngredientLog schema changes.
        migrations.CreateModel(
            name='IngredientLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('sale', 'Sale'), ('void', 'Void'), ('adjustment', 'Adjustment'), ('restock', 'Restock')], max_length=20)),
                ('quantity_change', models.DecimalField(decimal_places=4, max_digits=10)),
                ('stock_before', models.DecimalField(decimal_places=4, max_digits=10)),
                ('stock_after', models.DecimalField(decimal_places=4, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='canteen.ingredient')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_logs', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_logs', to='canteen.postransaction')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
