# Generated by Django 5.2.14 on 2026-06-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0036_alter_postransaction_total_amount_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantgroup',
            name='max_selections',
            field=models.PositiveIntegerField(blank=True, help_text='Max selections allowed (multi only)', null=True),
        ),
        migrations.AddField(
            model_name='variantgroup',
            name='min_selections',
            field=models.PositiveIntegerField(blank=True, help_text='Min selections required (multi only)', null=True),
        ),
    ]
