# Generated by Django 5.2.14 on 2026-06-02 14:54

import django.db.models.deletion
from django.db import migrations, models


def backfill_void_transaction_type(apps, schema_editor):
    """FEATURE-015: existing voided rows predate transaction_type. Mark them
    'void' so the new discriminator agrees with the legacy `void` flag. New
    code reads transaction_type; the `void` flag is kept for backward compat.
    """
    PosTransaction = apps.get_model('canteen', 'PosTransaction')
    PosTransaction.objects.filter(void=True).update(transaction_type='void')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0037_variantgroup_max_selections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransaction',
            name='refund_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='canteen.postransaction'),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('void', 'Void'), ('refund', 'Refund')], default='sale', max_length=10),
        ),
        migrations.AddField(
            model_name='zreport',
            name='refund_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zreport',
            name='refund_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ingredientlog',
            name='action',
            field=models.CharField(choices=[('sale', 'Sale'), ('void', 'Void'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('restock', 'Restock')], max_length=20),
        ),
        migrations.AlterField(
            model_name='postransaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('void', 'Void'), ('refunded', 'Refunded')], default='completed', max_length=20, verbose_name='Status'),
        ),
        migrations.RunPython(backfill_void_transaction_type, noop_reverse),
    ]
