# Generated by Django 5.2.14 on 2026-06-02 15:08

import django.db.models.deletion
from django.db import migrations, models


def backfill_payment_lines(apps, schema_editor):
    """FEATURE-016: give every existing transaction one PaymentLine covering
    its charged total, so the new PaymentLine-based X/Z aggregation has data
    for historical rows.

    The line's amount is the charged total (net_total) — equal to gross_total
    when there is no discount. Rows with a non-positive or missing net_total
    are skipped: refunds (FEATURE-015) carry a negative net_total and would
    violate the amount > 0 CheckConstraint, and they intentionally have no
    PaymentLines (refund cash is reconciled separately in the Z).
    """
    PosTransaction = apps.get_model('canteen', 'PosTransaction')
    PaymentLine = apps.get_model('canteen', 'PaymentLine')
    valid_methods = {'cash', 'card', 'gcash', 'maya'}
    lines = []
    qs = PosTransaction.objects.filter(net_total__gt=0).exclude(
        payment_lines__isnull=False
    )
    for txn in qs.iterator():
        method = txn.payment_method if txn.payment_method in valid_methods else 'cash'
        lines.append(PaymentLine(
            transaction=txn, method=method, amount=txn.net_total
        ))
        if len(lines) >= 500:
            PaymentLine.objects.bulk_create(lines)
            lines = []
    if lines:
        PaymentLine.objects.bulk_create(lines)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0038_postransaction_refund_of_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('gcash', 'GCash'), ('maya', 'Maya')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_lines', to='canteen.postransaction')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payline_positive')],
            },
        ),
        migrations.RunPython(backfill_payment_lines, noop_reverse),
    ]
