# Generated by Django 5.2.14 on 2026-06-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0041_alter_zreport_options_zcounter_accredited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='depletion_mode',
            field=models.CharField(choices=[('replace', 'Replace'), ('add', 'Add')], default='replace', max_length=7),
        ),
    ]
