# Generated by Django 5.2.14 on 2026-07-01 11:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0043_recipeingredient_per_item_variant_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='last_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='purchase_to_base_factor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='purchase_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_ingredients', to='canteen.ingredientunit'),
        ),
    ]
