# Generated by Django 5.2.14 on 2026-07-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0044_ingredient_purchase_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransactionitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
