# Generated by Django 5.2.14 on 2026-05-14 04:42

import pos.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_businessprofile_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='api_key',
            field=pos.fields.FernetEncryptedField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='api_secret',
            field=pos.fields.FernetEncryptedField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='merchant_id',
            field=pos.fields.FernetEncryptedField(blank=True, max_length=500, null=True),
        ),
    ]
