# Generated by Django 5.2.14 on 2026-06-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0034_ingredient_track_depletion_ingredient_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransaction',
            name='is_seed',
            field=models.BooleanField(default=False),
        ),
        # NOTE: makemigrations also wanted an AlterField on
        # postransaction.total_amount_currency (djmoney choices drift,
        # FLAG-065). That drift is intentionally NOT migrated — it is a
        # no-op choices-list expansion from a djmoney version bump. It has
        # been stripped (same procedure as 0034) so 0035 carries only the
        # FLAG-047 is_seed quarantine field.
    ]
