# Generated by Django 4.2 on 2026-06-02 13:50

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0035_postransaction_is_seed_and_more'),
    ]

    operations = [
        # FLAG-065: with settings.CURRENCIES = ('PHP',), djmoney now narrows the
        # currency choices to the single currency this POS uses. This is the
        # intentional drift the previous migrations (0034/0035) had to keep
        # stripping; applying it once here ends the recurring choices-list churn.
        migrations.AlterField(
            model_name='postransaction',
            name='total_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PHP', 'Philippine Peso')], default='PHP', editable=False, max_length=3),
        ),
    ]
