# Generated by Django 5.2.14 on 2026-06-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0039_paymentline'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='zero_rated',
            field=models.BooleanField(default=False, help_text='VAT-exempt item. Sale amount goes to zero_rated_sales; VAT is 0.', verbose_name='Zero-Rated (VAT-exempt)'),
        ),
    ]
