# Generated by Django 5.2.14 on 2026-06-02 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0040_item_zero_rated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zreport',
            options={'ordering': ['-reset_counter', '-z_counter']},
        ),
        migrations.AddField(
            model_name='zcounter',
            name='accredited_at',
            field=models.DateTimeField(blank=True, help_text='When the BIR accreditation reset was applied (null = not yet accredited).', null=True),
        ),
        migrations.AddField(
            model_name='zcounter',
            name='reset_by',
            field=models.ForeignKey(blank=True, help_text='User who applied the accreditation reset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accreditation_resets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zreport',
            name='z_counter',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='zreport',
            constraint=models.UniqueConstraint(fields=('reset_counter', 'z_counter'), name='zreport_unique_series_counter'),
        ),
    ]
