# Generated by Django 5.2.14 on 2026-07-03 11:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0045_postransactionitem_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='ingredient_management_enabled',
            field=models.BooleanField(default=True, verbose_name='Ingredient & Recipe Management'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='batch_yield',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_preparation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredientlog',
            name='action',
            field=models.CharField(choices=[('sale', 'Sale'), ('void', 'Void'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('restock', 'Restock'), ('production', 'Production')], max_length=20),
        ),
        migrations.CreateModel(
            name='PreparationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=4, max_digits=12)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_preparations', to='pos.ingredient')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='pos.ingredient')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('preparation', models.F('component')), _negated=True), name='prep_not_self_component'), models.UniqueConstraint(fields=('preparation', 'component'), name='uniq_preparation_component')],
            },
        ),
    ]
