# Generated by Django 5.2.14 on 2026-07-18 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0046_businessprofile_ingredient_management_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientrestocklog',
            name='corrected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredientrestocklog',
            name='corrected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredientrestocklog',
            name='correction_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ingredientrestocklog',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredientrestocklog',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredientrestocklog',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingredientlog',
            name='action',
            field=models.CharField(choices=[('sale', 'Sale'), ('void', 'Void'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('restock', 'Restock'), ('production', 'Production'), ('correction', 'Correction')], max_length=20),
        ),
    ]
