# Generated by Django 5.2.14 on 2026-07-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0047_ingredientrestocklog_corrected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientrestocklog',
            name='cost_before',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
