# Generated by Django 5.2.14 on 2026-07-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0048_ingredientrestocklog_cost_before'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='officialreceiptcounter',
            new_name='pos_officia_date_45bb26_idx',
            old_name='pos_off_date_d4adf3_idx',
        ),
        migrations.RenameIndex(
            model_name='postransaction',
            new_name='pos_postran_created_ab9192_idx',
            old_name='pos_pos_created_d66520_idx',
        ),
        migrations.RenameIndex(
            model_name='postransaction',
            new_name='pos_postran_transac_a5ea15_idx',
            old_name='pos_pos_transac_80ed38_idx',
        ),
        migrations.RenameIndex(
            model_name='postransaction',
            new_name='pos_postran_payment_d4a3b7_idx',
            old_name='pos_pos_payment_bd6710_idx',
        ),
        migrations.RenameIndex(
            model_name='zreport',
            new_name='pos_zreport_busines_e41f06_idx',
            old_name='pos_zre_busines_e8d618_idx',
        ),
        migrations.RenameIndex(
            model_name='zreport',
            new_name='pos_zreport_finaliz_a90ef4_idx',
            old_name='pos_zre_finaliz_85294c_idx',
        ),
    ]
