# Generated by Django 5.2.14 on 2026-08-14 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0049_rename_indexes_pos_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='zreport',
            name='cash_paid_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='zreport',
            name='cash_paid_out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='zreport',
            name='credit_extended',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='zreport',
            name='credit_settled',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentline',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('gcash', 'GCash'), ('maya', 'Maya'), ('credit', 'Credit / Unpaid')], max_length=10),
        ),
        migrations.AlterField(
            model_name='postransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('maya', 'Maya'), ('card', 'Card'), ('credit', 'Credit / Unpaid')], default='cash', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('drop', 'Cash drop / collection'), ('payout', 'Cash payout'), ('cash_in', 'Cash added'), ('settlement', 'Credit settlement')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to=settings.AUTH_USER_MODEL)),
                ('settles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='pos.postransaction')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='pos.shift')),
            ],
            options={
                'indexes': [models.Index(fields=['shift', 'kind'], name='pos_cashmov_shift_i_c5f01d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='cashmovement_positive')],
            },
        ),
    ]
