# Generated by Django 5.2.14 on 2026-08-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0050_feature059_cash_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='zreport',
            name='counted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
