# Generated by Django 5.2.14 on 2026-08-14 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0051_feature061_counted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='entry_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='entry_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_entries', to='pos.ingredientunit'),
        ),
        migrations.CreateModel(
            name='IngredientUnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_base_factor', models.DecimalField(decimal_places=6, max_digits=12)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='pos.ingredient')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.ingredientunit')),
            ],
            options={
                'ordering': ['ingredient__name', 'unit__abbreviation'],
                'constraints': [models.UniqueConstraint(fields=('ingredient', 'unit'), name='uniq_ingredient_unit_conv'), models.CheckConstraint(condition=models.Q(('to_base_factor__gt', 0)), name='unit_conv_factor_positive')],
            },
        ),
    ]
