# Generated by Django 5.2.14 on 2026-08-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0052_feature046_unit_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentline',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
