# Generated by Django 5.2.14 on 2026-08-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0053_feature059fu_payment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='default_credit_kind',
            field=models.CharField(choices=[('house', 'House (owner / family / staff)'), ('charge', 'Charge (to be settled)')], default='house', max_length=8, verbose_name='Default Credit Kind'),
        ),
        migrations.AddField(
            model_name='paymentline',
            name='credit_kind',
            field=models.CharField(blank=True, choices=[('house', 'House (owner / family / staff)'), ('charge', 'Charge (to be settled)')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='zreport',
            name='house_consumption',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
